version: '3.7'

services:
  keycloak-server1:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    command:
      - "start-dev"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://host.docker.internal:5432/keycloak"
      - "KC_DB_SCHEMA=public"
      - "KC_DB_USERNAME=postgres"
      - "KC_DB_PASSWORD=root"
    extra_hosts:
      - "host.docker.internal:host-gateway"